name: Create new Morpho Rewards

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  compute-market-distribution:
    name: Compute markets distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Sync snapshotBlock, initialBlock & finalBlock for epochs
        run: yarn updateAgesData
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

      - name: Commit synced snapshotBlock, initialBlock & finalBlock for epochs if needed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Morpho GitHub Actions Bot
          commit_user_email: dev@morpho.xyz
          commit_message: "feat: Sync snapshotBlock, initialBlock & finalBlock for epochs"

      - name: Compute Market Distribution
        run: yarn markets:emissions
        env:
          RPC_URL: ${{ secrets.RPC_URL }}

      - name: Commit new distribution to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Morpho GitHub Actions Bot
          commit_user_email: dev@morpho.xyz
          commit_message: "feat: Generate new distribution for rewards"
